name: adaptive_number
version: 1.0.2

description: >-
  Library providing an adaptive number implementation. On JS runtimes, a 64-bit signed fixed-width integer will be used and
  for all other platforms the default Dart int data type.
homepage: https://github.com/lemoony/adaptive_number_dart

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  fixnum: ^1.1.1

dev_dependencies:
  lint: ^2.3.0
  test: ^1.16.0
